import { ThemeProvider } from "@/components/theme-provider";

import type { Metadata } from "next";
import {
  Geist,
  Geist_Mono,
  Work_Sans,
  Quicksand,
  Questrial,
} from "next/font/google";
import "./globals.css";
import AuthContextProvider from "@/context/authContext";
import { Toaster } from "@/components/ui/sonner";
import AuthenticatedRoute from "@/auth/AuthenticatedRoute";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const workSans = Work_Sans({
  variable: "--font-work-sans",
  subsets: ["latin"],
});

const quicksand = Quicksand({
  variable: "--font-quicksand",
  subsets: ["latin"],
});

const questrial = Questrial({
  variable: "--font-questrial",
  weight: "400", // ✅ Required
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning className={quicksand.className}>
      <body className={` antialiased flex flex-col min-h-screen`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <AuthContextProvider>{children}</AuthContextProvider>
          <Footer />
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  );
}
